exports.handler = async function (event) {
  if (event.httpMethod !== 'POST') return json(405, { error: 'Method not allowed' });
  const key = process.env.DEEPSEEK_API_KEY;
  if (!key) return json(500, { error: 'The route-planning service is not configured on the server.' });
  let input;
  try { input = JSON.parse(event.body || '{}'); } catch { return json(400, { error: 'Invalid JSON request.' }); }
  const system = `You are an expert China travel planner. Return JSON only, with exactly {"routes":[...]} and exactly 3 routes. Every route must include title, description, daily_plan, estimated_cost and tips; daily_plan must contain exactly ${Number(input.days) || 1} days. The user's planning priorities are durable account settings: obey them in the supplied order before optimizing anything else, and explain the trade-off when priorities conflict. Respect interests, budget, pace, notes, mustDo and Want/Optional/Skip choices; never include Skip. The requested destination must remain the user's exact province/city/prefecture/county and must not be replaced with a nearby famous city. If the built-in destination knowledge is insufficient, perform broad public web research for current travel recommendations, including Xiaohongshu, Bilibili and Douyin creator itineraries where available, then propose only relevant key places for the user to choose or use. Clearly label research-based suggestions and tell the user to verify access, opening hours and booking rules. Use realistic geographic grouping and transport; never invent uncertain prices, hours or train times—say “verify before departure”. Use English for all user-facing output; Chinese names may appear in parentheses. daily_plan days can use {"day":1,"title":"...","activities":["..."],"transport":"...","meals":"..."}. estimated_cost should be a conservative range or explain its basis; tips must be an array of strings.`;
  const response = await fetch('https://api.deepseek.com/chat/completions', { method:'POST', headers:{'Content-Type':'application/json','Authorization':`Bearer ${key}`}, body:JSON.stringify({model:'deepseek-chat',temperature:0.85,response_format:{type:'json_object'},messages:[{role:'system',content:system},{role:'user',content:JSON.stringify(input)}]}) });
  const body = await response.json();
  if (!response.ok) return json(response.status, { error: body.error?.message || 'Route-planning request failed.' });
  try { const data=JSON.parse(body.choices?.[0]?.message?.content||'{}'); if(!Array.isArray(data.routes)||data.routes.length!==3) throw new Error('The route planner returned an invalid route count.'); return json(200,data); } catch { return json(502,{error:'The route planner returned data that could not be parsed.'}); }
};
function json(status, body) { return { statusCode:status, headers:{'Content-Type':'application/json','Cache-Control':'no-store'}, body:JSON.stringify(body) }; }
