const $=selector=>document.querySelector(selector);
const $$=selector=>[...document.querySelectorAll(selector)];
const esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[char]));
const money=value=>'¥'+Math.round(value).toLocaleString('en-US');
const zhSuffix=/(特别行政区|维吾尔自治区|壮族自治区|回族自治区|自治区|自治州|地区|盟|省|市|县|区)$/;
let pinyinFn=null,divisionData={},currentUser=null,currentPlans=[],selectedPlan=null,authMode='login',supabase=null;
let travelPrinciples=['Save time on transfers','See places unique to the destination','Eat well','Keep the plan reliable'];
let preferencesLoadedFor=null,priorityEditing=false,priorityDraft=[],draggedPriorityIndex=null;

// Keep trip-specific requests separate from the durable account-level ranking.
const mustDoField=document.createElement('label');mustDoField.innerHTML='Must-do experiences for this trip <span class="optional">optional</span><textarea id="mustDo" rows="3" placeholder="Example: Spend two full days finding photography locations and taking editorial portraits in Luoyang."></textarea>';$('#interestsPanel').append(mustDoField);
const hours=Array.from({length:24},(_,hour)=>String(hour).padStart(2,'0')+':00');const travelRhythm=document.createElement('fieldset');travelRhythm.className='travel-rhythm';travelRhythm.innerHTML='<legend>Design each day around your rhythm <small>Every choice below shapes your routes.</small></legend><div class="field-grid three"><label>Typical start time<select id="dailyStartTime">'+hours.map(time=>`<option value="${time}" ${time==='09:00'?'selected':''}>${time}</option>`).join('')+'</select></label><label>Typical finish time<select id="dailyEndTime">'+hours.map(time=>`<option value="${time}" ${time==='18:00'?'selected':''}>${time}</option>`).join('')+'</select></label><label>Daily travel pace<select id="dailyPace"><option value="Slow">Slow · fewer stops, more breathing room</option><option value="Balanced" selected>Balanced · highlights plus flexible time</option><option value="Fast">Fast · fit more into each day</option></select></label></div><div class="detail-level"><span>How detailed should the daily plan be?</span><label class="choice"><input type="radio" name="itineraryDetail" value="Precise timetable" checked><span>Precise timetable<br><small>Suggested times for each stop</small></span></label><label class="choice"><input type="radio" name="itineraryDetail" value="Day overview"><span>Day overview<br><small>A clear morning / afternoon / evening flow</small></span></label></div>';
$('#interestsPanel').insertBefore(travelRhythm,mustDoField);
const priorityPanel=document.createElement('section');priorityPanel.className='form-panel';priorityPanel.id='prioritiesPanel';priorityPanel.innerHTML='<div class="panel-number">P</div><div><p class="kicker">ACCOUNT SETTING · LONG-TERM</p><h3>Planning priority (长期规划偏好)</h3><p class="panel-intro">This ranking is attached to your account and stays the same until you change it. Your planning assistant considers it first when building every route.</p><p class="cloud-sync-status" id="priorityCloudStatus" role="status">Sign in to keep these priorities across devices.</p></div><fieldset class="preference-block"><legend>Planning priorities · highest first</legend><p class="priority-edit-hint" id="priorityEditHint">Select Edit to add, delete or reorder priorities.</p><div id="principleListStandalone" class="principle-list"></div><div class="add-principle" hidden><input id="customPrincipleStandalone" maxlength="48" placeholder="Add your own long-term priority"><button id="addPrincipleStandalone" class="ghost" type="button">Add</button></div></fieldset><div class="panel-actions"><button class="ghost" id="prioritiesNext" type="button">Edit</button></div>';
priorityPanel.hidden=true;document.body.append(priorityPanel);const homePriorityButton=document.createElement('button');homePriorityButton.className='priority-home-button';homePriorityButton.type='button';homePriorityButton.innerHTML='<span>Planning priority</span><small>Long-term travel preferences, applied consistently to every plan.</small>';$('.hero-actions').append(homePriorityButton);const closePriority=document.createElement('button');closePriority.className='priority-close';closePriority.type='button';closePriority.textContent='Close';priorityPanel.prepend(closePriority);homePriorityButton.addEventListener('click',()=>{priorityPanel.hidden=false;setPriorityEditing(false)});closePriority.addEventListener('click',()=>{setPriorityEditing(false);priorityPanel.hidden=true});

const provinceNames={'北京市':'Beijing Municipality 北京市','天津市':'Tianjin Municipality 天津市','河北省':'Hebei 河北省','山西省':'Shanxi 山西省','内蒙古自治区':'Inner Mongolia 内蒙古自治区','辽宁省':'Liaoning 辽宁省','吉林省':'Jilin 吉林省','黑龙江省':'Heilongjiang 黑龙江省','上海市':'Shanghai Municipality 上海市','江苏省':'Jiangsu 江苏省','浙江省':'Zhejiang 浙江省','安徽省':'Anhui 安徽省','福建省':'Fujian 福建省','江西省':'Jiangxi 江西省','山东省':'Shandong 山东省','河南省':'Henan 河南省','湖北省':'Hubei 湖北省','湖南省':'Hunan 湖南省','广东省':'Guangdong 广东省','广西壮族自治区':'Guangxi 广西壮族自治区','海南省':'Hainan 海南省','重庆市':'Chongqing Municipality 重庆市','四川省':'Sichuan 四川省','贵州省':'Guizhou 贵州省','云南省':'Yunnan 云南省','西藏自治区':'Tibet 西藏自治区','陕西省':'Shaanxi 陕西省','甘肃省':'Gansu 甘肃省','青海省':'Qinghai 青海省','宁夏回族自治区':'Ningxia 宁夏回族自治区','新疆维吾尔自治区':'Xinjiang 新疆维吾尔自治区','香港特别行政区':'Hong Kong 香港特别行政区','澳门特别行政区':'Macao 澳门特别行政区','台湾省':'Taiwan 台湾省'};
const exactNames={'杭州市':'Hangzhou 杭州','杭州':'Hangzhou 杭州','北京市':'Beijing 北京','上海市':'Shanghai 上海','西安市':'Xi’an 西安','成都市':'Chengdu 成都','桂林市':'Guilin 桂林','张家界市':'Zhangjiajie 张家界','拉萨市':'Lhasa 拉萨','重庆市':'Chongqing 重庆','苏州市':'Suzhou 苏州','南京市':'Nanjing 南京','昆明市':'Kunming 昆明','大理白族自治州':'Dali 大理','丽江市':'Lijiang 丽江','厦门市':'Xiamen 厦门','广州市':'Guangzhou 广州','深圳市':'Shenzhen 深圳','青岛市':'Qingdao 青岛','普洱市':'Pu’er 普洱','阿坝藏族羌族自治州':'Ngawa (Aba) 阿坝州','天津市':'Tianjin 天津','香港特别行政区':'Hong Kong 香港','澳门特别行政区':'Macao 澳门'};
const popularLocations={Beijing:['北京市','北京市'],Shanghai:['上海市','上海市'],"Xi'an":['陕西省','西安市'],Chengdu:['四川省','成都市'],Guilin:['广西壮族自治区','桂林市'],Hangzhou:['浙江省','杭州市'],Zhangjiajie:['湖南省','张家界市'],Lhasa:['西藏自治区','拉萨市']};
const destinationProfiles={
  Beijing:{zh:'北京',mood:'IMPERIAL · LIVING HISTORY',image:'https://images.unsplash.com/photo-1508804185872-d7badad00f7d?auto=format&fit=crop&w=1000&q=82',description:'Walk through imperial China, then turn a corner into hutong life, contemporary art and one of the world’s most exciting food cities.',sights:['Forbidden City 故宫','Temple of Heaven 天坛','Summer Palace 颐和园','Mutianyu Great Wall 慕田峪长城','Shichahai 什刹海','798 Art District 798艺术区'],foods:['Jianbing breakfast 煎饼','Beijing roast duck 北京烤鸭','Zhajiang noodles 炸酱面'],stay:'Dongcheng or near a Line 2 metro station 东城区'},
  Shanghai:{zh:'上海',mood:'FUTURE · ART DECO · STREET LIFE',image:'https://images.unsplash.com/photo-1548919973-5cef591cdbc9?auto=format&fit=crop&w=1000&q=82',description:'See China at its most global: Art Deco streets, ambitious museums, riverside skylines and tiny neighborhood restaurants.',sights:['The Bund 外滩','Yu Garden 豫园','Former French Concession 法租界','West Bund 西岸','Shanghai Museum 上海博物馆','Zhujiajiao 朱家角'],foods:['Shengjian buns 生煎','Shanghai noodles 葱油拌面','Benbang cuisine 本帮菜'],stay:'People’s Square or the Former French Concession'},
  "Xi'an":{zh:'西安',mood:'SILK ROAD · TANG DYNASTY',image:'https://images.unsplash.com/photo-1591122947157-26bad3a117d2?auto=format&fit=crop&w=1000&q=82',description:'Meet the beginning of the Silk Road through archaeology, city walls, Muslim-quarter flavors and Tang-dynasty spectacle.',sights:['Terracotta Army 兵马俑','Xi’an City Wall 西安城墙','Giant Wild Goose Pagoda 大雁塔','Shaanxi History Museum 陕西历史博物馆','Muslim Quarter 回民街','Datang Everbright City 大唐不夜城'],foods:['Roujiamo 肉夹馍','Biangbiang noodles 油泼面','Shaanxi tasting dinner 陕菜'],stay:'Inside the City Wall or near Yongningmen 永宁门'},
  Chengdu:{zh:'成都',mood:'PANDAS · TEAHOUSES · SPICE',image:'https://images.unsplash.com/photo-1537531383496-f4749b8032cf?auto=format&fit=crop&w=1000&q=82',description:'Slow down into teahouse culture, Sichuan flavors, leafy parks, creative neighborhoods and an early morning with giant pandas.',sights:['Chengdu Panda Base 熊猫基地','People’s Park 人民公园','Wuhou Shrine 武侯祠','Jinsha Site Museum 金沙遗址','Eastern Suburb Memory 东郊记忆','Qingcheng Mountain 青城山'],foods:['Dandan noodles 担担面','Sichuan hotpot 四川火锅','Mapo tofu 麻婆豆腐'],stay:'Chunxi Road or Tianfu Square 春熙路 / 天府广场'},
  Guilin:{zh:'桂林',mood:'KARST · RIVERS · RICE TERRACES',image:'https://images.unsplash.com/photo-1528127269322-539801943592?auto=format&fit=crop&w=1000&q=82',description:'Move through ink-painting landscapes by boat, bicycle and foot, with limestone peaks, village lanes and rice terraces.',sights:['Li River 漓江','Yangshuo 阳朔','Longji Rice Terraces 龙脊梯田','Xianggong Hill 相公山','Two Rivers and Four Lakes 两江四湖','Reed Flute Cave 芦笛岩'],foods:['Guilin rice noodles 桂林米粉','Beer fish 啤酒鱼','Oil tea 油茶'],stay:'Central Guilin first, then Yangshuo 桂林 / 阳朔'},
  Hangzhou:{zh:'杭州',mood:'LAKE · TEA · SOUTHERN SONG',image:'https://images.unsplash.com/photo-1598880940080-ff9a29891b85?auto=format&fit=crop&w=1000&q=82',description:'Discover a graceful China of lake paths, tea hills, Buddhist carvings, Southern Song stories and refined regional food.',sights:['West Lake 西湖','Lingyin Temple 灵隐寺','Longjing Tea Village 龙井村','Xixi Wetland 西溪湿地','Grand Canal 大运河','China Academy of Art 中国美术学院'],foods:['Pian’erchuan noodles 片儿川','Longjing shrimp 龙井虾仁','Lotus root starch 西湖藕粉'],stay:'Lakeside or near Fengqi Road 湖滨 / 凤起路'},
  Zhangjiajie:{zh:'张家界',mood:'SANDSTONE · CLOUD FORESTS',image:'https://images.unsplash.com/photo-1605640840605-14ac1855827b?auto=format&fit=crop&w=1000&q=82',description:'Enter a vertical world of sandstone pillars, glass bridges and cloud forests that looks almost too cinematic to be real.',sights:['Zhangjiajie National Forest Park 张家界国家森林公园','Tianmen Mountain 天门山','Yuanjiajie 袁家界','Golden Whip Stream 金鞭溪','Grand Canyon Glass Bridge 大峡谷玻璃桥','Baofeng Lake 宝峰湖'],foods:['Tujia three-pot stew 三下锅','Smoked pork 土家腊肉','Rice wine 米酒'],stay:'Wulingyuan for the park, downtown for Tianmen Mountain 武陵源'},
  Lhasa:{zh:'拉萨',mood:'TIBETAN PLATEAU · PILGRIMAGE',image:'https://images.unsplash.com/photo-1564329494258-3f72215ba175?auto=format&fit=crop&w=1000&q=82',description:'Travel slowly at altitude through sacred architecture, pilgrimage circuits and vast plateau light unlike anywhere else.',sights:['Potala Palace 布达拉宫','Jokhang Temple 大昭寺','Barkhor Street 八廓街','Sera Monastery 色拉寺','Norbulingka 罗布林卡','Yamdrok Lake 羊卓雍错'],foods:['Sweet tea 甜茶','Tibetan noodles 藏面','Yak hotpot 牦牛肉火锅'],stay:'Near Barkhor with a quiet room 八廓街周边'},
};

Object.assign(popularLocations,{Chongqing:['重庆市','重庆市'],Dali:['云南省','大理白族自治州'],Suzhou:['江苏省','苏州市'],Xiamen:['福建省','厦门市'],Harbin:['黑龙江省','哈尔滨市'],Kunming:['云南省','昆明市']});
Object.assign(destinationProfiles,{
  Chongqing:{zh:'重庆',mood:'MOUNTAIN CITY · NIGHT LIGHTS · HOTPOT',image:destinationProfiles.Chengdu.image,description:'Ride hillside monorails, cross layered riverfront streets and taste one of China’s boldest food cultures in a city built vertically.',sights:['Hongya Cave 洪崖洞','Liziba Monorail Station 李子坝','Three Gorges Museum 三峡博物馆','Ciqikou Ancient Town 磁器口','Wulong Karst 武隆喀斯特','Yangtze River Cableway 长江索道'],foods:['Chongqing hotpot 重庆火锅','Xiaomian noodles 重庆小面','Sour and spicy rice noodles 酸辣粉'],stay:'Jiefangbei or near Xiaoshizi metro 解放碑 / 小什字'},
  Dali:{zh:'大理',mood:'ERHAI LAKE · BAI CULTURE · MOUNTAINS',image:destinationProfiles.Guilin.image,description:'Balance old-town lanes with lakeside cycling, Bai villages and the dramatic Cangshan range above Erhai Lake.',sights:['Dali Ancient Town 大理古城','Erhai Lake 洱海','Cangshan Mountain 苍山','Xizhou Ancient Town 喜洲古镇','Shuanglang 双廊','Three Pagodas 崇圣寺三塔'],foods:['Rushan cheese 乳扇','Bai-style fish 白族酸辣鱼','Xizhou baba 喜洲粑粑'],stay:'Dali Ancient Town or Caicun 大理古城 / 才村'},
  Suzhou:{zh:'苏州',mood:'CLASSICAL GARDENS · CANALS · SILK',image:destinationProfiles.Hangzhou.image,description:'Move slowly through scholar gardens, canal neighborhoods and refined Jiangnan craft traditions just beyond Shanghai.',sights:['Humble Administrator’s Garden 拙政园','Suzhou Museum 苏州博物馆','Tiger Hill 虎丘','Pingjiang Road 平江路','Master of the Nets Garden 网师园','Tongli Water Town 同里'],foods:['Squirrel-shaped mandarin fish 松鼠桂鱼','Suzhou noodles 苏式汤面','Sweet osmanthus cake 桂花糕'],stay:'Gusu District near Pingjiang Road 姑苏区 / 平江路'},
  Xiamen:{zh:'厦门',mood:'ISLANDS · ARCADES · COASTAL LIFE',image:destinationProfiles.Shanghai.image,description:'Enjoy a gentle coastal city of island gardens, shaded lanes, Fujian flavors and easy access to Hakka tulou country.',sights:['Gulangyu Island 鼓浪屿','South Putuo Temple 南普陀寺','Shapowei 沙坡尾','Xiamen Botanical Garden 厦门园林植物园','Zhongshan Road 中山路','Fujian Tulou 福建土楼'],foods:['Shacha noodles 沙茶面','Oyster omelette 海蛎煎','Peanut soup 花生汤'],stay:'Siming District near Zhongshan Road 思明区 / 中山路'},
  Harbin:{zh:'哈尔滨',mood:'WINTER CITY · ARCHITECTURE · NORTHEAST',image:destinationProfiles.Beijing.image,description:'Discover grand streets, hearty northeastern food and—in winter—one of the world’s great ice-and-snow spectacles.',sights:['Harbin Ice and Snow World 哈尔滨冰雪大世界','Central Street 中央大街','Saint Sophia Cathedral 圣索菲亚教堂','Sun Island 太阳岛','Chinese Baroque Historic Block 中华巴洛克历史文化街区','Siberian Tiger Park 东北虎林园'],foods:['Guobaorou 锅包肉','Harbin red sausage 哈尔滨红肠','Madier ice cream 马迭尔冰棍'],stay:'Daoli District near Central Street 道里区 / 中央大街'},
  Kunming:{zh:'昆明',mood:'SPRING CITY · FLOWERS · YUNNAN FLAVORS',image:destinationProfiles.Lhasa.image,description:'Use China’s Spring City as a relaxed gateway to Yunnan, with lakes, flower markets, stone forests and extraordinary regional food.',sights:['Green Lake Park 翠湖公园','Yunnan Provincial Museum 云南省博物馆','Dounan Flower Market 斗南花市','Stone Forest 石林','Western Hills 西山','Guandu Ancient Town 官渡古镇'],foods:['Crossing-the-bridge noodles 过桥米线','Wild mushroom hotpot 野生菌火锅','Steam-pot chicken 汽锅鸡'],stay:'Near Dongfeng Square or Green Lake 东风广场 / 翠湖'}
});

const commonsImage=file=>`https://commons.wikimedia.org/wiki/Special:Redirect/file/${encodeURIComponent(file)}?width=1200`;
const commonsPage=file=>`https://commons.wikimedia.org/wiki/File:${encodeURIComponent(file).replaceAll('%2F','/')}`;
const verifiedPhotos={
  Beijing:['Peking verbotene Stadt-20071018-RM-162900.jpg','Forbidden City viewed from Jingshan Hill'],
  Shanghai:['Shanghai Skyline from the Bund.jpg','Shanghai skyline from the Bund'],
  "Xi'an":['1 xian city wall 2011.jpg','Xi’an City Wall panorama'],
  Chengdu:['Chengdu Research Base of Giant Panda Breeding, 201907, 09.jpg','Giant panda at Chengdu Research Base'],
  Guilin:['Guilin Li River.jpg','Karst scenery along the Li River'],
  Hangzhou:['West Lake Panorama at Dusk.jpg','West Lake at dusk'],
  Zhangjiajie:['Zhangjiajie, National park - panoramio.jpg','Sandstone pillars in Zhangjiajie National Forest Park'],
  Lhasa:['Potala Palace Lhasa Tibet Autonomous Region China 西藏 拉萨 布达拉宫 - panoramio.jpg','Potala Palace in Lhasa'],
  Chongqing:['Hongya Cave at night 20251027 (1).jpg','Hongya Cave at night'],
  Dali:['LandscapeDali.jpg','Dali old town, Cangshan and Erhai landscape'],
  Suzhou:['Classical Gardens of Suzhou pavilion, August 2016.jpg','Pavilion in a classical Suzhou garden'],
  Xiamen:['厦门鼓浪屿轮渡望鼓浪屿地标 - 日光岩 - panoramio.jpg','Gulangyu Island and Sunlight Rock'],
  Harbin:['St. Sophia Cathedral, Harbin, China.jpg','Saint Sophia Cathedral in Harbin'],
  Kunming:['20260222 the Big Stone Forest.jpg','The Stone Forest near Kunming']
};
Object.entries(verifiedPhotos).forEach(([key,[file,alt]])=>Object.assign(destinationProfiles[key],{image:commonsImage(file),imageAlt:alt,credit:'Photo: Wikimedia Commons',creditUrl:commonsPage(file)}));
Object.assign(destinationProfiles,{
  'Pu’er':{zh:'普洱',mood:'ANCIENT TEA FORESTS · COFFEE · ETHNIC VILLAGES',description:'Follow tea and coffee from forest to cup, with time in Blang villages and the UNESCO-listed cultural landscape of Jingmai Mountain.',sights:['Jingmai Mountain Ancient Tea Forest 景迈山古茶林文化景观','Wengji Blang Ancient Village 翁基布朗族古寨','Nuogang Ancient Village 糯岗古寨','Nakeli Tea-Horse Road 那柯里茶马古道','Xiao’aozi Coffee Estate 小凹子咖啡庄园','China Pu’er Tea Museum 中华普洱茶博览苑'],foods:['Pu’er vinegar rice noodles 普洱醋米线','Wa-style chicken rice 佤味鸡肉烂饭','Local coffee and aged Pu’er tea 普洱咖啡与茶'],stay:'Simao for transport, then one night near Jingmai Mountain 思茅 / 景迈山',routeNote:'Jingmai sights are dispersed and public transport is limited. A pre-booked driver or self-drive is more realistic than ride-hailing on the mountain.',researchUrl:'https://search.bilibili.com/all?keyword=%E6%99%AF%E8%BF%88%E5%B1%B1%E6%97%85%E6%B8%B8%E6%94%BB%E7%95%A5'},
  'Ngawa (Aba)':{zh:'阿坝州',mood:'ALPINE LAKES · TIBETAN & QIANG CULTURE · HIGH PLATEAU',description:'Build one coherent highland circuit instead of collecting distant sights: turquoise lakes, snow peaks, grasslands and Tibetan–Qiang communities.',sights:['Jiuzhaigou Valley 九寨沟','Huanglong Scenic Area 黄龙','Mount Siguniang 四姑娘山','Bipenggou Valley 毕棚沟','Dagu Glacier 达古冰川','Ruoergai Grassland 若尔盖草原'],foods:['Yak hotpot 牦牛肉火锅','Tibetan barley dishes 青稞餐','Qiang-style cured pork 羌味腊肉'],stay:'Stay near the scenic area chosen for each leg; avoid one fixed base in this vast prefecture',routeNote:'Distances are long and elevations change quickly. Combine nearby sights, keep the first day gentle and never put Jiuzhaigou, Siguniang and Ruoergai into one rushed day.',researchUrl:'https://search.bilibili.com/all?keyword=%E9%98%BF%E5%9D%9D%E6%97%85%E6%B8%B8%E8%B7%AF%E7%BA%BF'}
});

function toast(message){const node=$('#toast');node.textContent=String(message);node.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>node.classList.remove('show'),3600)}
function englishName(zh){if(!zh)return'';if(exactNames[zh])return exactNames[zh];if(provinceNames[zh])return provinceNames[zh];const short=zh.replace(zhSuffix,'');if(pinyinFn){const words=pinyinFn(short,{toneType:'none',type:'array'});const roman=words.map(word=>word.charAt(0).toUpperCase()+word.slice(1)).join(' ');return roman+' '+zh}return 'China destination '+zh}
function cityKeyFromDestination(value){return Object.keys(destinationProfiles).find(key=>value.includes(key)||value.includes(destinationProfiles[key].zh))}
function genericProfile(destination){const english=destination.split(/\s(?=[\u3400-\u9fff])/)[0]||destination;return{zh:destination.match(/[\u3400-\u9fff]+/)?.[0]||'',mood:'LOCAL CHINA · DISCOVERY',description:'Explore '+english+' through its best-known landscapes, local culture and everyday flavors. Each stop is marked for live map verification before booking.',sights:[`Official landmark in ${destination}`,`Local cultural site in ${destination}`,`Signature natural scenery near ${destination}`,`Historic neighborhood in ${destination}`,`Local craft or food experience in ${destination}`,`Easy day trip from ${destination}`],foods:[`Local breakfast in ${destination}`,`Regional specialty meal in ${destination}`,`Local tea or dessert in ${destination}`],stay:`Central ${destination}, close to the main transport hub`}}
function getProfile(destination){const key=cityKeyFromDestination(destination);return key?destinationProfiles[key]:genericProfile(destination)}

const exportActions=document.createElement('div');exportActions.className='itinerary-export-actions';exportActions.innerHTML='<button class="ghost" id="saveItineraryPdf" type="button">Save as PDF</button><button class="primary" id="saveItineraryImage" type="button">Save itinerary image</button>';$('.final-edit-actions').after(exportActions);
function loadHtml2Canvas(){if(window.html2canvas)return Promise.resolve(window.html2canvas);return new Promise((resolve,reject)=>{const script=document.createElement('script');script.src='https://cdn.jsdelivr.net/npm/html2canvas@1.4.1/dist/html2canvas.min.js';script.onload=()=>resolve(window.html2canvas);script.onerror=()=>reject(new Error('Image export could not load. Check your internet connection and try again.'));document.head.append(script)})}
$('#saveItineraryPdf').addEventListener('click',()=>window.print());
$('#saveItineraryImage').addEventListener('click',async event=>{const button=event.currentTarget;button.disabled=true;button.textContent='Preparing image…';try{const html2canvas=await loadHtml2Canvas();document.body.classList.add('exporting-itinerary');await new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve)));const canvas=await html2canvas($('#finalPlan'),{scale:2,backgroundColor:'#f7edd5',useCORS:true,logging:false});document.body.classList.remove('exporting-itinerary');const link=document.createElement('a');link.download='china-itinerary-'+new Date().toISOString().slice(0,10)+'.png';link.href=canvas.toDataURL('image/png');link.click();toast('Itinerary image saved to your device.')}catch(error){document.body.classList.remove('exporting-itinerary');console.error(error);toast(error.message||'Image export failed. Please try again.')}finally{button.disabled=false;button.textContent='Save itinerary image'}});
const routeGenerationOverlay=document.createElement('section');routeGenerationOverlay.className='route-generation-overlay';routeGenerationOverlay.setAttribute('aria-live','polite');routeGenerationOverlay.innerHTML='<div class="route-generation-card"><p class="kicker">YOUR PERSONAL PLAN IS TAKING SHAPE</p><h2>Building your three routes</h2><p id="routeGenerationMessage">Reading your destination and trip details.</p><div class="route-progress-track" aria-hidden="true"><span id="routeGenerationProgress"></span></div><div class="route-generation-steps"><span>Preferences</span><span>Route logic</span><span>Daily plans</span></div><small>This usually takes 10–30 seconds. Keep this page open while we finish.</small></div>';document.body.append(routeGenerationOverlay);
function showRouteGeneration(){const progress=$('#routeGenerationProgress'),message=$('#routeGenerationMessage');clearInterval(showRouteGeneration.timer);routeGenerationOverlay.classList.add('show');progress.style.width='16%';message.textContent='Reading your destination and trip details.';let stage=0;const stages=[['Balancing your long-term priorities with this trip.',48],['Building realistic daily route options.',74],['Writing three distinct itineraries for you.',90]];showRouteGeneration.timer=setInterval(()=>{const next=stages[stage++];if(!next){clearInterval(showRouteGeneration.timer);return}message.textContent=next[0];progress.style.width=next[1]+'%'},2600)}
function hideRouteGeneration(){clearInterval(showRouteGeneration.timer);$('#routeGenerationProgress').style.width='100%';setTimeout(()=>routeGenerationOverlay.classList.remove('show'),220)}
let currentFlowStep=0,maxUnlockedFlowStep=1;
function unlockFlow(step){maxUnlockedFlowStep=Math.max(maxUnlockedFlowStep,step)}
function showFlowStep(step){
  if(step<=6&&step>maxUnlockedFlowStep){toast('Complete the current step before moving ahead.');return}
  currentFlowStep=step;document.body.classList.add('flow-mode');document.body.dataset.flowStep=String(step);
  $$('.journey-axis button').forEach(button=>{const value=+button.dataset.flowStep;button.disabled=value>maxUnlockedFlowStep;button.classList.toggle('active',value===step);button.classList.toggle('complete',value<step&&value<=maxUnlockedFlowStep)});
  $('#axisProgress').style.width=`${Math.min(step,6)/6*100}%`;window.scrollTo({top:0,behavior:'smooth'});
}
$$('.journey-axis button').forEach(button=>button.addEventListener('click',()=>showFlowStep(+button.dataset.flowStep)));
$$('[data-go-step]').forEach(button=>button.addEventListener('click',()=>showFlowStep(+button.dataset.goStep)));
$('.hero-actions .primary').addEventListener('click',event=>{event.preventDefault();unlockFlow(1);showFlowStep(1)});
$('.hero-actions .hero-secondary').addEventListener('click',event=>{event.preventDefault();unlockFlow(2);showFlowStep(2)});
$('.site-header nav a[href="#discover"]').addEventListener('click',event=>{event.preventDefault();unlockFlow(1);showFlowStep(1)});
$('.site-header nav a[href="#planner"]').addEventListener('click',event=>{event.preventDefault();unlockFlow(2);showFlowStep(2)});
$('.site-header nav a[href="#saved"]').addEventListener('click',event=>{event.preventDefault();showFlowStep(7)});
$('#destinationNext').addEventListener('click',()=>{if(!$('#province').value||!$('#prefecture').value)return toast('Choose a province and city first.');unlockFlow(3);showFlowStep(3)});
$('#prioritiesNext').addEventListener('click',async event=>{
  if(!priorityEditing){setPriorityEditing(true);return}
  if(!priorityDraft.length)return toast('Add at least one planning priority before saving.');
  const button=event.currentTarget;button.disabled=true;button.textContent='Saving…';
  const previous=[...travelPrinciples];travelPrinciples=[...priorityDraft];
  const saved=!currentUser||!supabase||await persistUserPreferences();
  button.disabled=false;
  if(!saved){travelPrinciples=previous;button.textContent='Save';return}
  setPriorityEditing(false);priorityPanel.hidden=true;
  toast(currentUser?'Planning priorities saved to your account.':'Planning priorities saved for this session.');
});
$('#detailsNext').addEventListener('click',()=>{if(!$('#origin').value.trim())return toast('Choose or enter your starting point.');if(!$('#startDate').value||!$('#endDate').value)return toast('Choose your travel dates.');if(new Date($('#endDate').value)<new Date($('#startDate').value))return toast('Your end date must be after the start date.');renderAdvancedPreferences();unlockFlow(4);showFlowStep(4)});

function showCity(key){const data=destinationProfiles[key];if(!data)return;$$('.city-bubble').forEach(button=>button.classList.toggle('active',button.dataset.city===key));$('#previewImage').src=data.image;$('#previewImage').alt=data.imageAlt||key+' travel scenery';$('#previewMood').textContent=data.mood;$('#previewName').innerHTML=esc(key)+' <small>'+esc(data.zh)+'</small>';$('#previewDescription').textContent=data.description;$('#previewPlan').innerHTML='Plan a '+esc(key)+' trip <span>→</span>';$('#previewPlan').dataset.city=key;$('#previewCredit').textContent=data.credit||'Representative travel photo';$('#previewCredit').href=data.creditUrl||data.image}
$$('.city-bubble').forEach(button=>{button.addEventListener('mouseenter',()=>showCity(button.dataset.city));button.addEventListener('focus',()=>showCity(button.dataset.city));button.addEventListener('click',()=>showCity(button.dataset.city))});
$('#previewPlan').addEventListener('click',()=>{selectPopularCity($('#previewPlan').dataset.city||'Beijing');unlockFlow(2);showFlowStep(2)});
$('#browseAllCities').addEventListener('click',()=>{unlockFlow(2);showFlowStep(2)});

function fillSelect(select,items,placeholder,formatter=englishName){select.innerHTML='<option value="">'+placeholder+'</option>'+items.map(item=>'<option value="'+esc(item)+'">'+esc(formatter(item))+'</option>').join('')}
function addSpecialRegions(){divisionData['香港特别行政区']||={'香港特别行政区':['中西区','湾仔区','油尖旺区','九龙城区','离岛区']};divisionData['澳门特别行政区']||={'澳门特别行政区':['大堂区','望德堂区','风顺堂区','嘉模堂区','路凼填海区']};divisionData['台湾省']||={'台北市':['中正区','大安区','信义区','士林区','北投区'],'台中市':['中区','西区','北屯区','西屯区'],'台南市':['中西区','安平区','东区'],'高雄市':['新兴区','三民区','左营区'],'花莲县':['花莲市','新城乡','寿丰乡'],'台东县':['台东市','成功镇','池上乡']}}
function updateDestination(){const province=$('#province').value,city=$('#prefecture').value,county=$('#county').value;const path=[province,city,county].filter(Boolean);const chosen=county||city||province;const label=path.join(' → ');$('#destination').value=label;$('#selectionSummary').textContent='Selected: '+label}
function updateCounties(){const items=divisionData[$('#province').value]?.[$('#prefecture').value]||[];fillSelect($('#county'),items,'Whole city / area');updateDestination()}
function updateCities(){const items=Object.keys(divisionData[$('#province').value]||{});fillSelect($('#prefecture'),items,'Choose a city or area');$('#county').innerHTML='<option value="">Whole city / area</option>';updateDestination()}
async function selectPopularCity(key){const pair=popularLocations[key];if(!pair||!divisionData[pair[0]])return;$('#province').value=pair[0];updateCities();$('#prefecture').value=pair[1];updateCounties();updateDestination()}

async function initDivisions(){
  const pinyinReady=import('https://esm.sh/pinyin-pro@3.27.0').then(module=>{
    pinyinFn=module.pinyin;
    if(Object.keys(divisionData).length){
      const province=$('#province').value,city=$('#prefecture').value,county=$('#county').value;
      fillSelect($('#province'),Object.keys(divisionData),'Choose a province or region');
      $('#province').value=province;updateCities();$('#prefecture').value=city;updateCounties();$('#county').value=county;updateDestination();
    }
  }).catch(error=>console.warn('Pinyin helper unavailable; using bilingual fallbacks.',error));
  try{const response=await fetch('./pca.json');if(!response.ok)throw new Error('Region data could not be loaded.');divisionData=await response.json();addSpecialRegions();fillSelect($('#province'),Object.keys(divisionData),'Choose a province or region');$('#province').value='浙江省';updateCities();$('#prefecture').value='杭州市';updateCounties()}catch(error){$('#province').innerHTML='<option value="浙江省">Zhejiang 浙江省</option>';$('#prefecture').innerHTML='<option value="杭州市">Hangzhou 杭州</option>';$('#county').innerHTML='<option value="">Whole city / area</option>';updateDestination();toast('Region list is temporarily unavailable. Hangzhou is ready to plan.')}
  void pinyinReady;
}
$('#province').addEventListener('change',updateCities);$('#prefecture').addEventListener('change',updateCounties);$('#county').addEventListener('change',updateDestination);
$$('.step').forEach(button=>button.addEventListener('click',()=>{$$('.step').forEach(item=>item.classList.toggle('active',item===button));$('#'+button.dataset.stepTarget).scrollIntoView({behavior:'smooth',block:'center'})}));

const worldOrigins=[
  'New York, United States','Los Angeles, United States','San Francisco, United States','Chicago, United States','Seattle, United States','Boston, United States','Washington, D.C., United States','Honolulu, United States','Toronto, Canada','Vancouver, Canada','Montreal, Canada','Mexico City, Mexico','São Paulo, Brazil','Rio de Janeiro, Brazil','Buenos Aires, Argentina','Santiago, Chile','Lima, Peru',
  'London, United Kingdom','Paris, France','Amsterdam, Netherlands','Brussels, Belgium','Berlin, Germany','Frankfurt, Germany','Munich, Germany','Madrid, Spain','Barcelona, Spain','Lisbon, Portugal','Rome, Italy','Milan, Italy','Zurich, Switzerland','Vienna, Austria','Prague, Czechia','Warsaw, Poland','Copenhagen, Denmark','Stockholm, Sweden','Oslo, Norway','Helsinki, Finland','Dublin, Ireland','Athens, Greece','Istanbul, Türkiye','Moscow, Russia',
  'Tokyo, Japan','Osaka, Japan','Seoul, South Korea','Singapore','Bangkok, Thailand','Kuala Lumpur, Malaysia','Jakarta, Indonesia','Bali, Indonesia','Manila, Philippines','Hanoi, Vietnam','Ho Chi Minh City, Vietnam','Phnom Penh, Cambodia','Delhi, India','Mumbai, India','Bengaluru, India','Kathmandu, Nepal','Dubai, United Arab Emirates','Doha, Qatar','Tel Aviv, Israel','Riyadh, Saudi Arabia',
  'Sydney, Australia','Melbourne, Australia','Brisbane, Australia','Perth, Australia','Auckland, New Zealand','Cairo, Egypt','Cape Town, South Africa','Johannesburg, South Africa','Nairobi, Kenya','Casablanca, Morocco','Lagos, Nigeria',
  'Beijing, China','Shanghai, China','Guangzhou, China','Shenzhen, China','Hong Kong, China','Macao, China','Taipei, Taiwan'
];
$('#worldOrigins').innerHTML=worldOrigins.map(city=>`<option value="${esc(city)}"></option>`).join('');
$('#locationHelp').textContent='Only after you click: your browser asks permission, then coordinates are sent once to our location lookup provider to identify the nearest city. We do not save the coordinates. You can always search worldwide instead.';
$('#locateOrigin').addEventListener('click',()=>{
  const button=$('#locateOrigin'),status=$('#locationStatus');
  if(!navigator.geolocation){status.textContent='Location is not supported in this browser. Search for your city instead.';return}
  button.disabled=true;button.querySelector('span').textContent='Locating…';status.textContent='Your browser will ask for permission.';
  navigator.geolocation.getCurrentPosition(async position=>{
    const {latitude,longitude}=position.coords;
    try{
      const response=await fetch(`https://api.bigdatacloud.net/data/reverse-geocode-client?latitude=${latitude}&longitude=${longitude}&localityLanguage=en`);
      if(!response.ok)throw new Error('Location lookup failed');
      const place=await response.json(),city=place.city||place.locality||place.principalSubdivision||'Current location',country=place.countryName||'';
      $('#origin').value=[city,country].filter(Boolean).join(', ');status.textContent=`Located near ${$('#origin').value}. You can edit this before planning.`;toast('Starting point added from your location.')
    }catch(error){status.textContent='We found your position but could not identify the city. Search for a nearby city instead.'}
    button.disabled=false;button.querySelector('span').textContent='Use my location';
  },error=>{
    status.textContent=error.code===1?'Location permission was not granted. Search for your city instead.':'We could not determine your location. Search for your city instead.';
    button.disabled=false;button.querySelector('span').textContent='Use my location';
  },{enableHighAccuracy:false,timeout:12000,maximumAge:300000});
});

function setPriorityEditing(editing){
  priorityEditing=editing;draggedPriorityIndex=null;
  if(editing)priorityDraft=[...travelPrinciples];else priorityDraft=[];
  const button=$('#prioritiesNext'),addRow=$('#customPrincipleStandalone').closest('.add-principle');
  button.textContent=editing?'Save':'Edit';button.classList.toggle('primary',editing);button.classList.toggle('ghost',!editing);
  addRow.hidden=!editing;$('#priorityEditHint').textContent=editing?'Drag the handle to reorder. Changes are saved only when you select Save.':'Select Edit to add, delete or reorder priorities.';
  priorityPanel.classList.toggle('is-editing',editing);renderAdvancedPreferences();
}
function renderAdvancedPreferences(){
  const principles=priorityEditing?priorityDraft:travelPrinciples;
  $('#principleListStandalone').innerHTML=principles.map((item,index)=>`<div class="principle-row${priorityEditing?' editable':''}" data-priority-index="${index}" draggable="${priorityEditing}"><span class="priority-drag-handle" aria-hidden="true">⋮⋮</span><b>P${index+1}</b><span>${esc(item)}</span>${priorityEditing?`<button class="priority-delete" type="button" data-priority-delete="${index}" aria-label="Delete ${esc(item)}">Delete</button>`:''}</div>`).join('');
}
$('#principleListStandalone').addEventListener('click',event=>{const button=event.target.closest('[data-priority-delete]');if(!button||!priorityEditing)return;priorityDraft.splice(+button.dataset.priorityDelete,1);renderAdvancedPreferences()});
$('#principleListStandalone').addEventListener('dragstart',event=>{const row=event.target.closest('[data-priority-index]');if(!priorityEditing||!row)return event.preventDefault();draggedPriorityIndex=+row.dataset.priorityIndex;row.classList.add('dragging');event.dataTransfer.effectAllowed='move';event.dataTransfer.setData('text/plain',String(draggedPriorityIndex))});
$('#principleListStandalone').addEventListener('dragover',event=>{if(draggedPriorityIndex===null)return;event.preventDefault();event.dataTransfer.dropEffect='move';$$('#principleListStandalone .drag-over').forEach(row=>row.classList.remove('drag-over'));event.target.closest('[data-priority-index]')?.classList.add('drag-over')});
$('#principleListStandalone').addEventListener('dragleave',event=>event.target.closest('[data-priority-index]')?.classList.remove('drag-over'));
$('#principleListStandalone').addEventListener('drop',event=>{event.preventDefault();const row=event.target.closest('[data-priority-index]'),targetIndex=row?+row.dataset.priorityIndex:priorityDraft.length-1;if(draggedPriorityIndex===null||targetIndex===draggedPriorityIndex)return;const [moved]=priorityDraft.splice(draggedPriorityIndex,1);priorityDraft.splice(targetIndex,0,moved);draggedPriorityIndex=null;renderAdvancedPreferences()});
$('#principleListStandalone').addEventListener('dragend',()=>{draggedPriorityIndex=null;$$('#principleListStandalone .principle-row').forEach(row=>row.classList.remove('dragging','drag-over'))});
$('#addPrincipleStandalone').addEventListener('click',()=>{if(!priorityEditing)return;const input=$('#customPrincipleStandalone'),value=input.value.trim();if(!value)return;if(priorityDraft.includes(value))return toast('That priority is already in the list.');priorityDraft.push(value);input.value='';renderAdvancedPreferences()});
$('#customPrincipleStandalone').addEventListener('keydown',event=>{if(event.key==='Enter'){event.preventDefault();$('#addPrincipleStandalone').click()}});

function tripInput(){const start=new Date($('#startDate').value),end=new Date($('#endDate').value);const days=Math.max(1,Math.round((end-start)/86400000)+1);const destination=$('#destination').value;return{destination,location:{province:$('#province').value,city:$('#prefecture').value,county:$('#county').value||null,path:[$('#province').value,$('#prefecture').value,$('#county').value].filter(Boolean)},startDate:$('#startDate').value,endDate:$('#endDate').value,days,travelers:Math.max(1,+$('#travelers').value||1),budget:$('#budget').value,transport:$('#transport').value,origin:$('#origin').value.trim()||'your arrival point',interests:$$('#interestChips input:checked').map(input=>input.value),principles:[...travelPrinciples],notes:$('#notes').value.trim(),mustDo:$('#mustDo')?.value.trim()||'',profile:getProfile(destination)}}
const baseTripInput=tripInput;tripInput=function(){const input=baseTripInput(),dailyStartTime=$('#dailyStartTime').value,dailyEndTime=$('#dailyEndTime').value,dailyPace=$('#dailyPace').value,itineraryDetail=$('input[name="itineraryDetail"]:checked').value;input.dailyWindow={start:dailyStartTime,end:dailyEndTime};input.dailyPace=dailyPace;input.itineraryDetail=itineraryDetail;input.notes=[input.notes,`Daily travel window: ${dailyStartTime} to ${dailyEndTime}.`,`Daily pace: ${dailyPace}.`,`Itinerary detail: ${itineraryDetail}.`].filter(Boolean).join(' ');return input};
function formatEstimatedCost(value){if(typeof value==='string')return value;if(typeof value==='number')return money(value);if(value&&typeof value==='object')return Object.entries(value).map(([key,item])=>`${key.replaceAll('_',' ')}: ${typeof item==='object'?JSON.stringify(item):item}`).join(' · ');return'Verify before booking'}
function compactEstimatedCost(value){
  const text=String(value||'Verify before booking').replace(/\s+/g,' ').trim();
  const amount=text.split(/\s*·\s*|\s*\|\s*|\s+basis\s*:/i)[0]
    .replace(/^(?:estimated\s+)?(?:trip\s+)?(?:cost\s+)?range\s*:\s*/i,'')
    .trim();
  return amount||'Verify before booking';
}
function normalizeAiRoute(route,input,index){const rawDays=Array.isArray(route.daily_plan)?route.daily_plan:[];const days=Array.from({length:input.days},(_,i)=>{const raw=rawDays[i]||{},rawActivities=Array.isArray(raw.activities)?raw.activities:[raw.morning,raw.afternoon,raw.evening].filter(Boolean),activities=rawActivities.map(activity=>typeof activity==='string'?activity:[activity?.time,activity?.title||activity?.activity,activity?.description].filter(Boolean).join(' · ')).filter(Boolean),a=activities[0]||raw.title||'Local exploration',b=activities[1]||activities[2]||'Flexible time and transfer buffer',timeline=activities.map((activity,activityIndex)=>[`Stop ${activityIndex+1}`,activity]);if(raw.transport)timeline.push(['Transport',raw.transport]);if(raw.meals)timeline.push(['Meals',raw.meals]);if(raw.summary)timeline.push(['Day note',raw.summary]);return{a,b,food:raw.meals||'Local specialties',cost:{transport:0,stay:0,food:0,sights:0,total:0},timeline:timeline.length?timeline:[['Plan',`${a}; ${b}`]]}});return{name:route.title||`Personal route ${index+1}`,label:['PERSONALIZED','LOCAL DEPTH','EASY PACE'][index]||'PERSONAL ROUTE',summary:route.description||'A personalized route based on your choices.',days,aiRoute:route,estimatedCost:formatEstimatedCost(route.estimated_cost),tips:route.tips}}
function renderAiRoutes(input,routes){currentPlans=routes.slice(0,3).map((route,index)=>normalizeAiRoute(route,input,index));$('#resultsIntro').textContent=`${input.days} days in ${input.destination} · ${input.travelers} traveler${input.travelers>1?'s':''} · Priority: ${input.principles[0]||'your preferences'}`;$('#routeGrid').innerHTML=currentPlans.map((plan,index)=>`<article class="route-card ${index===0?'featured':''}"><span class="route-badge">${esc(plan.label)}</span><p class="kicker">${String(index+1).padStart(2,'0')} / ITINERARY</p><h3>${esc(plan.name)}</h3><p>${esc(plan.summary)}</p><div class="route-facts"><span>Daily plan <b>${input.days} days</b></span><span>Transport <b>${esc(input.transport)}</b></span><span>Cost <b>${esc(typeof plan.estimatedCost==='string'?plan.estimatedCost:'See plan')}</b></span></div><ol class="route-preview">${plan.days.slice(0,3).map((day,dayIndex)=>`<li>Day ${dayIndex+1}: ${esc(day.a)}</li>`).join('')}</ol><p class="route-price">${esc(Array.isArray(plan.tips)?plan.tips.join(' · '):(plan.tips||''))}</p><button class="primary select-route" data-plan="${index}" type="button">Choose this itinerary <span>→</span></button></article>`).join('');$$('.select-route').forEach(button=>button.addEventListener('click',()=>selectRoute(+button.dataset.plan,input)));$('#results').classList.remove('hidden');$('#finalPlan').classList.add('hidden');$('#results').scrollIntoView({behavior:'smooth'})}
function selectRoute(index,input){
  unlockFlow(6);showFlowStep(6);selectedPlan=currentPlans[index];
  const totals=selectedPlan.days.reduce((sum,day)=>{Object.keys(sum).forEach(key=>sum[key]+=day.cost[key]);return sum},{transport:0,stay:0,food:0,sights:0,total:0});
  Object.keys(totals).forEach(key=>totals[key]*=input.travelers);
  $('#finalSubtitle').textContent=`${selectedPlan.name} · ${input.days} days · ${input.destination}`;
  $('#budgetStrip').classList.toggle('ai-budget',Boolean(selectedPlan.aiRoute));
  $('#budgetStrip').innerHTML=selectedPlan.aiRoute
    ?[['Estimated trip cost',compactEstimatedCost(selectedPlan.estimatedCost)],['Travelers',String(input.travelers)],['Planning basis','Conservative estimate']].map(item=>`<div class="budget-item"><small>${item[0]}</small><b>${esc(item[1])}</b></div>`).join('')
    :[['Transport',totals.transport],['Stays',totals.stay],['Food',totals.food],['Sights',totals.sights],['Trip total',totals.total]].map(item=>`<div class="budget-item"><small>${item[0]}</small><b>${money(item[1])}</b></div>`).join('');
  $('#dayList').innerHTML=selectedPlan.days.map((day,dayIndex)=>`<article class="day-card"><div class="day-index"><small>DAY</small>${String(dayIndex+1).padStart(2,'0')}</div><div><h3>${esc(day.a)} + ${esc(day.b)}</h3><div class="timeline">${day.timeline.map(row=>`<div class="timeline-row"><b>${row[0]}</b><span>${esc(row[1])}</span></div>`).join('')}</div><div class="day-meta">${selectedPlan.aiRoute?`<div><b>Transport</b>${esc(input.transport)}</div><div><b>Stay area</b>${esc(input.profile.stay)}</div><div><b>Meals</b>${esc(day.food)}</div>`:`<div><b>Transport</b>${esc(input.transport)} · ${money(day.cost.transport*input.travelers)}</div><div><b>Stay</b>${esc(input.profile.stay)} · ${money(day.cost.stay*input.travelers)}</div><div><b>Food + sights</b>${money((day.cost.food+day.cost.sights)*input.travelers)}</div>`}</div></div></article>`).join('');
  $('#mapCheck').href='https://uri.amap.com/search?keyword='+encodeURIComponent(input.destination)+'&src=china-trip-planner';
  $('#finalPlan').classList.remove('hidden');$('#finalPlan').scrollIntoView({behavior:'smooth'});saveChosenPlan(input,selectedPlan,totals);toast('Your detailed China itinerary is ready.');
}
let generatingRoutes=false;
$('#tripForm').addEventListener('submit',async event=>{
  event.preventDefault();
  if(generatingRoutes)return;
  if(!$('#province').value||!$('#prefecture').value)return toast('Choose a province and city first.');
  const input=tripInput();
  if(!input.startDate||!input.endDate||input.days<1)return toast('Choose valid travel dates.');
  generatingRoutes=true;
  const submit=event.submitter;
  if(submit)submit.disabled=true;
  showRouteGeneration();
  const controller=new AbortController();
  const timeout=setTimeout(()=>controller.abort(),55000);
  try{
    const response=await fetch('/api/deepseek',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(input),signal:controller.signal});
    const raw=await response.text();
    let payload;
    try{payload=raw?JSON.parse(raw):{}}catch{throw new Error(location.hostname==='localhost'?'This local address is not running the route-planning function. Start the site with netlify dev and open the URL it prints.':`The route planner returned an invalid server response (${response.status}). Please try again.`)}
    if(!response.ok)throw new Error(payload.error||`Route planning failed (${response.status}). Please try again.`);
    if(!Array.isArray(payload.routes)||payload.routes.length!==3)throw new Error('The route planner did not return all three itineraries. Please try again.');
    renderAiRoutes(input,payload.routes);
    unlockFlow(5);
    showFlowStep(5);
  }catch(error){
    console.error(error);
    toast(error.name==='AbortError'?'Route planning took too long. Please try once more.':error.message||'Route planning failed. Please try again.');
  }finally{
    clearTimeout(timeout);
    generatingRoutes=false;
    if(submit)submit.disabled=false;
    hideRouteGeneration();
  }
});
$('#editTrip').addEventListener('click',()=>showFlowStep(2));
$('#revisePreferences').addEventListener('click',()=>{renderAdvancedPreferences();showFlowStep(4)});

function localPlans(){try{return JSON.parse(localStorage.getItem('chinaTripPlans')||'[]')}catch{return[]}}
function renderSaved(plans=localPlans()){if(!plans.length){if(currentUser){$('#savedTrips').className='empty-state';$('#savedTrips').innerHTML='<p>No cloud trips yet. Choose an itinerary and it will appear here on every device.</p>'}return}$('#savedTrips').className='';$('#savedTrips').innerHTML=plans.map(plan=>`<article class="saved-trip"><div><b>${esc(plan.destination)}</b><br><small>${esc(plan.name)} · ${plan.days} days · ${new Date(plan.savedAt).toLocaleDateString('en-US')}</small></div><span>${money(plan.total)}</span></article>`).join('')}
function setPreferenceCloudStatus(message,state=''){const node=$('#priorityCloudStatus');if(!node)return;node.textContent=message;node.dataset.state=state}
function preferencePayload(){return{user_id:currentUser.id,planning_priorities:[...travelPrinciples],updated_at:new Date().toISOString()}}
async function persistUserPreferences(){if(!currentUser||!supabase||preferencesLoadedFor!==currentUser.id)return false;setPreferenceCloudStatus('Saving preferences to your account…','saving');const {error}=await supabase.from('user_travel_preference_settings').upsert(preferencePayload(),{onConflict:'user_id'});if(error){console.warn('Preference sync failed.',error);setPreferenceCloudStatus('Could not save. Nothing was changed in your account.','error');return false}setPreferenceCloudStatus('Saved to your account. These preferences will return on your next sign-in.','saved');return true}
async function loadUserPreferences(){if(!currentUser||!supabase)return;setPreferenceCloudStatus('Loading your saved priorities…','loading');const userId=currentUser.id,{data,error}=await supabase.from('user_travel_preference_settings').select('planning_priorities').eq('user_id',userId).maybeSingle();if(currentUser?.id!==userId)return;if(error){console.warn('Preference load failed.',error);preferencesLoadedFor=userId;setPreferenceCloudStatus('Cloud priorities are temporarily unavailable.','error');return}if(Array.isArray(data?.planning_priorities)&&data.planning_priorities.length)travelPrinciples=[...data.planning_priorities];renderAdvancedPreferences();preferencesLoadedFor=userId;setPreferenceCloudStatus(data?'Saved priorities restored from your account.':'Changes here will be saved to your account automatically.',data?'saved':'ready')}
async function loadCloudPlans(){if(!currentUser||!supabase)return;const userId=currentUser.id,{data,error}=await supabase.from('user_travel_plan_history').select('id,destination,route_name,plan_data,created_at').eq('user_id',userId).order('created_at',{ascending:false}).limit(50);if(currentUser?.id!==userId)return;if(error){console.warn('Cloud trip history unavailable.',error);renderSaved();return}const plans=(data||[]).map(row=>{const payload=row.plan_data||{},input=payload.input||{},plan=payload.plan||{},totals=payload.totals||{};return{destination:row.destination,name:row.route_name,days:input.days||plan.days?.length||1,total:totals.total||0,savedAt:row.created_at}});renderSaved(plans)}
async function saveChosenPlan(input,plan,totals){const record={destination:input.destination,name:plan.name,days:input.days,total:totals.total,savedAt:new Date().toISOString()};const existing=localPlans().filter(item=>!(item.destination===record.destination&&item.name===record.name));localStorage.setItem('chinaTripPlans',JSON.stringify([record,...existing].slice(0,8)));renderSaved();if(currentUser&&supabase){const {error}=await supabase.from('user_travel_plan_history').insert({user_id:currentUser.id,destination:input.destination,route_name:plan.name,plan_data:{input,plan,totals}});if(error){console.warn('Cloud save unavailable; plan remains saved on this device.',error);return}await loadCloudPlans()}}

function openAuth(){if(currentUser){toast('You are already signed in.');return}$('#authDialog').showModal()}$('#authButton').addEventListener('click',openAuth);$('#savedAuthButton').addEventListener('click',openAuth);
function setAuthMode(mode){authMode=mode;$$('[data-auth-mode]').forEach(button=>button.classList.toggle('active',button.dataset.authMode===mode));$('#confirmLabel').classList.toggle('hidden',mode!=='register');$('#authSubmit').textContent=mode==='register'?'Create account':'Sign in';$('#authStatus').textContent=''}$$('[data-auth-mode]').forEach(button=>button.addEventListener('click',()=>setAuthMode(button.dataset.authMode)));
async function initAuth(){try{const module=await import('https://esm.sh/@supabase/supabase-js@2.57.4');supabase=module.createClient('https://snsfmpcomwkrqcofbssa.supabase.co','sb_publishable_bDB5kn2d3f9azvxvGlDMfg_HSoZSD84');const {data}=await supabase.auth.getSession();if(data.session)await showUser(data.session.user);supabase.auth.onAuthStateChange((_event,session)=>{if(session&&session.user.id!==currentUser?.id)void showUser(session.user)})}catch(error){console.warn('Account service unavailable; trip planning still works.',error);setPreferenceCloudStatus('Account sync is temporarily unavailable.','error')}}
async function showUser(user){currentUser=user;const name=user.user_metadata?.username||'Traveler';$('#authButton').textContent=name+' · Signed in';if($('#authDialog').open)$('#authDialog').close();await Promise.all([loadUserPreferences(),loadCloudPlans()]);toast('Welcome back, '+name+'.')}
$('#authForm').addEventListener('submit',async event=>{event.preventDefault();if(!supabase)return $('#authStatus').textContent='Account service is temporarily unavailable. You can still plan as a guest.';const username=$('#username').value.trim(),password=$('#password').value;if(!/^[A-Za-z0-9_]{3,24}$/.test(username))return $('#authStatus').textContent='Use 3–24 letters, numbers or underscores.';if(authMode==='register'&&password!==$('#confirmPassword').value)return $('#authStatus').textContent='Passwords do not match.';$('#authStatus').textContent=authMode==='register'?'Creating your account…':'Signing you in…';const email=username.toLowerCase()+'@travel-planner.app';const result=authMode==='register'?await supabase.auth.signUp({email,password,options:{data:{username}}}):await supabase.auth.signInWithPassword({email,password});if(result.error)return $('#authStatus').textContent=(authMode==='register'?'Account creation failed. ':'Sign-in failed. ')+result.error.message;if(result.data.session&&result.data.user.id!==currentUser?.id)await showUser(result.data.user);else if(!result.data.session) $('#authStatus').textContent='Account created. Sign in to continue.'});

const today=new Date(),end=new Date();end.setDate(today.getDate()+4);$('#startDate').value=today.toISOString().slice(0,10);$('#endDate').value=end.toISOString().slice(0,10);showCity('Beijing');renderSaved();showFlowStep(0);await initDivisions();initAuth();
