const $=selector=>document.querySelector(selector);
const $$=selector=>[...document.querySelectorAll(selector)];
const esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[char]));
const money=value=>'¥'+Math.round(value).toLocaleString('en-US');
const zhSuffix=/(特别行政区|维吾尔自治区|壮族自治区|回族自治区|自治区|自治州|地区|盟|省|市|县|区)$/;
let pinyinFn=null,divisionData={},currentUser=null,currentPlans=[],selectedPlan=null,authMode='login',supabase=null;

const provinceNames={'北京市':'Beijing Municipality 北京市','天津市':'Tianjin Municipality 天津市','河北省':'Hebei 河北省','山西省':'Shanxi 山西省','内蒙古自治区':'Inner Mongolia 内蒙古自治区','辽宁省':'Liaoning 辽宁省','吉林省':'Jilin 吉林省','黑龙江省':'Heilongjiang 黑龙江省','上海市':'Shanghai Municipality 上海市','江苏省':'Jiangsu 江苏省','浙江省':'Zhejiang 浙江省','安徽省':'Anhui 安徽省','福建省':'Fujian 福建省','江西省':'Jiangxi 江西省','山东省':'Shandong 山东省','河南省':'Henan 河南省','湖北省':'Hubei 湖北省','湖南省':'Hunan 湖南省','广东省':'Guangdong 广东省','广西壮族自治区':'Guangxi 广西壮族自治区','海南省':'Hainan 海南省','重庆市':'Chongqing Municipality 重庆市','四川省':'Sichuan 四川省','贵州省':'Guizhou 贵州省','云南省':'Yunnan 云南省','西藏自治区':'Tibet 西藏自治区','陕西省':'Shaanxi 陕西省','甘肃省':'Gansu 甘肃省','青海省':'Qinghai 青海省','宁夏回族自治区':'Ningxia 宁夏回族自治区','新疆维吾尔自治区':'Xinjiang 新疆维吾尔自治区','香港特别行政区':'Hong Kong 香港特别行政区','澳门特别行政区':'Macao 澳门特别行政区','台湾省':'Taiwan 台湾省'};
const exactNames={'杭州市':'Hangzhou 杭州','杭州':'Hangzhou 杭州','北京市':'Beijing 北京','上海市':'Shanghai 上海','西安市':'Xi’an 西安','成都市':'Chengdu 成都','桂林市':'Guilin 桂林','张家界市':'Zhangjiajie 张家界','拉萨市':'Lhasa 拉萨','重庆市':'Chongqing 重庆','苏州市':'Suzhou 苏州','南京市':'Nanjing 南京','昆明市':'Kunming 昆明','大理白族自治州':'Dali 大理','丽江市':'Lijiang 丽江','厦门市':'Xiamen 厦门','广州市':'Guangzhou 广州','深圳市':'Shenzhen 深圳','青岛市':'Qingdao 青岛','普洱市':'Pu’er 普洱','阿坝藏族羌族自治州':'Ngawa (Aba) 阿坝州','天津市':'Tianjin 天津','香港特别行政区':'Hong Kong 香港','澳门特别行政区':'Macao 澳门'};
const popularLocations={Beijing:['北京市','北京市'],Shanghai:['上海市','上海市'],"Xi'an":['陕西省','西安市'],Chengdu:['四川省','成都市'],Guilin:['广西壮族自治区','桂林市'],Hangzhou:['浙江省','杭州市'],Zhangjiajie:['湖南省','张家界市'],Lhasa:['西藏自治区','拉萨市']};
const destinationProfiles={
  Beijing:{zh:'北京',mood:'IMPERIAL · LIVING HISTORY',image:'https://images.unsplash.com/photo-1508804185872-d7badad00f7d?auto=format&fit=crop&w=1000&q=82',description:'Walk through imperial China, then turn a corner into hutong life, contemporary art and one of the world’s most exciting food cities.',sights:['Forbidden City 故宫','Temple of Heaven 天坛','Summer Palace 颐和园','Mutianyu Great Wall 慕田峪长城','Shichahai 什刹海','798 Art District 798艺术区'],foods:['Jianbing breakfast 煎饼','Beijing roast duck 北京烤鸭','Zhajiang noodles 炸酱面'],stay:'Dongcheng or near a Line 2 metro station 东城区'},
  Shanghai:{zh:'上海',mood:'FUTURE · ART DECO · STREET LIFE',image:'https://images.unsplash.com/photo-1548919973-5cef591cdbc9?auto=format&fit=crop&w=1000&q=82',description:'See China at its most global: Art Deco streets, ambitious museums, riverside skylines and tiny neighborhood restaurants.',sights:['The Bund 外滩','Yu Garden 豫园','Former French Concession 法租界','West Bund 西岸','Shanghai Museum 上海博物馆','Zhujiajiao 朱家角'],foods:['Shengjian buns 生煎','Shanghai noodles 葱油拌面','Benbang cuisine 本帮菜'],stay:'People’s Square or the Former French Concession'},
  "Xi'an":{zh:'西安',mood:'SILK ROAD · TANG DYNASTY',image:'https://images.unsplash.com/photo-1591122947157-26bad3a117d2?auto=format&fit=crop&w=1000&q=82',description:'Meet the beginning of the Silk Road through archaeology, city walls, Muslim-quarter flavors and Tang-dynasty spectacle.',sights:['Terracotta Army 兵马俑','Xi’an City Wall 西安城墙','Giant Wild Goose Pagoda 大雁塔','Shaanxi History Museum 陕西历史博物馆','Muslim Quarter 回民街','Datang Everbright City 大唐不夜城'],foods:['Roujiamo 肉夹馍','Biangbiang noodles 油泼面','Shaanxi tasting dinner 陕菜'],stay:'Inside the City Wall or near Yongningmen 永宁门'},
  Chengdu:{zh:'成都',mood:'PANDAS · TEAHOUSES · SPICE',image:'https://images.unsplash.com/photo-1537531383496-f4749b8032cf?auto=format&fit=crop&w=1000&q=82',description:'Slow down into teahouse culture, Sichuan flavors, leafy parks, creative neighborhoods and an early morning with giant pandas.',sights:['Chengdu Panda Base 熊猫基地','People’s Park 人民公园','Wuhou Shrine 武侯祠','Jinsha Site Museum 金沙遗址','Eastern Suburb Memory 东郊记忆','Qingcheng Mountain 青城山'],foods:['Dandan noodles 担担面','Sichuan hotpot 四川火锅','Mapo tofu 麻婆豆腐'],stay:'Chunxi Road or Tianfu Square 春熙路 / 天府广场'},
  Guilin:{zh:'桂林',mood:'KARST · RIVERS · RICE TERRACES',image:'https://images.unsplash.com/photo-1528127269322-539801943592?auto=format&fit=crop&w=1000&q=82',description:'Move through ink-painting landscapes by boat, bicycle and foot, with limestone peaks, village lanes and rice terraces.',sights:['Li River 漓江','Yangshuo 阳朔','Longji Rice Terraces 龙脊梯田','Xianggong Hill 相公山','Two Rivers and Four Lakes 两江四湖','Reed Flute Cave 芦笛岩'],foods:['Guilin rice noodles 桂林米粉','Beer fish 啤酒鱼','Oil tea 油茶'],stay:'Central Guilin first, then Yangshuo 桂林 / 阳朔'},
  Hangzhou:{zh:'杭州',mood:'LAKE · TEA · SOUTHERN SONG',image:'https://images.unsplash.com/photo-1598880940080-ff9a29891b85?auto=format&fit=crop&w=1000&q=82',description:'Discover a graceful China of lake paths, tea hills, Buddhist carvings, Southern Song stories and refined regional food.',sights:['West Lake 西湖','Lingyin Temple 灵隐寺','Longjing Tea Village 龙井村','Xixi Wetland 西溪湿地','Grand Canal 大运河','China Academy of Art 中国美术学院'],foods:['Pian’erchuan noodles 片儿川','Longjing shrimp 龙井虾仁','Lotus root starch 西湖藕粉'],stay:'Lakeside or near Fengqi Road 湖滨 / 凤起路'},
  Zhangjiajie:{zh:'张家界',mood:'SANDSTONE · CLOUD FORESTS',image:'https://images.unsplash.com/photo-1605640840605-14ac1855827b?auto=format&fit=crop&w=1000&q=82',description:'Enter a vertical world of sandstone pillars, glass bridges and cloud forests that looks almost too cinematic to be real.',sights:['Zhangjiajie National Forest Park 张家界国家森林公园','Tianmen Mountain 天门山','Yuanjiajie 袁家界','Golden Whip Stream 金鞭溪','Grand Canyon Glass Bridge 大峡谷玻璃桥','Baofeng Lake 宝峰湖'],foods:['Tujia three-pot stew 三下锅','Smoked pork 土家腊肉','Rice wine 米酒'],stay:'Wulingyuan for the park, downtown for Tianmen Mountain 武陵源'},
  Lhasa:{zh:'拉萨',mood:'TIBETAN PLATEAU · PILGRIMAGE',image:'https://images.unsplash.com/photo-1564329494258-3f72215ba175?auto=format&fit=crop&w=1000&q=82',description:'Travel slowly at altitude through sacred architecture, pilgrimage circuits and vast plateau light unlike anywhere else.',sights:['Potala Palace 布达拉宫','Jokhang Temple 大昭寺','Barkhor Street 八廓街','Sera Monastery 色拉寺','Norbulingka 罗布林卡','Yamdrok Lake 羊卓雍错'],foods:['Sweet tea 甜茶','Tibetan noodles 藏面','Yak hotpot 牦牛肉火锅'],stay:'Near Barkhor with a quiet room 八廓街周边'},
};

Object.assign(popularLocations,{Chongqing:['重庆市','重庆市'],Dali:['云南省','大理白族自治州'],Suzhou:['江苏省','苏州市'],Xiamen:['福建省','厦门市'],Harbin:['黑龙江省','哈尔滨市'],Kunming:['云南省','昆明市']});
Object.assign(destinationProfiles,{
  Chongqing:{zh:'重庆',mood:'MOUNTAIN CITY · NIGHT LIGHTS · HOTPOT',image:destinationProfiles.Chengdu.image,description:'Ride hillside monorails, cross layered riverfront streets and taste one of China’s boldest food cultures in a city built vertically.',sights:['Hongya Cave 洪崖洞','Liziba Monorail Station 李子坝','Three Gorges Museum 三峡博物馆','Ciqikou Ancient Town 磁器口','Wulong Karst 武隆喀斯特','Yangtze River Cableway 长江索道'],foods:['Chongqing hotpot 重庆火锅','Xiaomian noodles 重庆小面','Sour and spicy rice noodles 酸辣粉'],stay:'Jiefangbei or near Xiaoshizi metro 解放碑 / 小什字'},
  Dali:{zh:'大理',mood:'ERHAI LAKE · BAI CULTURE · MOUNTAINS',image:destinationProfiles.Guilin.image,description:'Balance old-town lanes with lakeside cycling, Bai villages and the dramatic Cangshan range above Erhai Lake.',sights:['Dali Ancient Town 大理古城','Erhai Lake 洱海','Cangshan Mountain 苍山','Xizhou Ancient Town 喜洲古镇','Shuanglang 双廊','Three Pagodas 崇圣寺三塔'],foods:['Rushan cheese 乳扇','Bai-style fish 白族酸辣鱼','Xizhou baba 喜洲粑粑'],stay:'Dali Ancient Town or Caicun 大理古城 / 才村'},
  Suzhou:{zh:'苏州',mood:'CLASSICAL GARDENS · CANALS · SILK',image:destinationProfiles.Hangzhou.image,description:'Move slowly through scholar gardens, canal neighborhoods and refined Jiangnan craft traditions just beyond Shanghai.',sights:['Humble Administrator’s Garden 拙政园','Suzhou Museum 苏州博物馆','Tiger Hill 虎丘','Pingjiang Road 平江路','Master of the Nets Garden 网师园','Tongli Water Town 同里'],foods:['Squirrel-shaped mandarin fish 松鼠桂鱼','Suzhou noodles 苏式汤面','Sweet osmanthus cake 桂花糕'],stay:'Gusu District near Pingjiang Road 姑苏区 / 平江路'},
  Xiamen:{zh:'厦门',mood:'ISLANDS · ARCADES · COASTAL LIFE',image:destinationProfiles.Shanghai.image,description:'Enjoy a gentle coastal city of island gardens, shaded lanes, Fujian flavors and easy access to Hakka tulou country.',sights:['Gulangyu Island 鼓浪屿','South Putuo Temple 南普陀寺','Shapowei 沙坡尾','Xiamen Botanical Garden 厦门园林植物园','Zhongshan Road 中山路','Fujian Tulou 福建土楼'],foods:['Shacha noodles 沙茶面','Oyster omelette 海蛎煎','Peanut soup 花生汤'],stay:'Siming District near Zhongshan Road 思明区 / 中山路'},
  Harbin:{zh:'哈尔滨',mood:'WINTER CITY · ARCHITECTURE · NORTHEAST',image:destinationProfiles.Beijing.image,description:'Discover grand streets, hearty northeastern food and—in winter—one of the world’s great ice-and-snow spectacles.',sights:['Harbin Ice and Snow World 哈尔滨冰雪大世界','Central Street 中央大街','Saint Sophia Cathedral 圣索菲亚教堂','Sun Island 太阳岛','Chinese Baroque Historic Block 中华巴洛克历史文化街区','Siberian Tiger Park 东北虎林园'],foods:['Guobaorou 锅包肉','Harbin red sausage 哈尔滨红肠','Madier ice cream 马迭尔冰棍'],stay:'Daoli District near Central Street 道里区 / 中央大街'},
  Kunming:{zh:'昆明',mood:'SPRING CITY · FLOWERS · YUNNAN FLAVORS',image:destinationProfiles.Lhasa.image,description:'Use China’s Spring City as a relaxed gateway to Yunnan, with lakes, flower markets, stone forests and extraordinary regional food.',sights:['Green Lake Park 翠湖公园','Yunnan Provincial Museum 云南省博物馆','Dounan Flower Market 斗南花市','Stone Forest 石林','Western Hills 西山','Guandu Ancient Town 官渡古镇'],foods:['Crossing-the-bridge noodles 过桥米线','Wild mushroom hotpot 野生菌火锅','Steam-pot chicken 汽锅鸡'],stay:'Near Dongfeng Square or Green Lake 东风广场 / 翠湖'}
});

function toast(message){const node=$('#toast');node.textContent=message;node.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>node.classList.remove('show'),2400)}
function englishName(zh){if(!zh)return'';if(exactNames[zh])return exactNames[zh];if(provinceNames[zh])return provinceNames[zh];const short=zh.replace(zhSuffix,'');if(pinyinFn){const words=pinyinFn(short,{toneType:'none',type:'array'});const roman=words.map(word=>word.charAt(0).toUpperCase()+word.slice(1)).join(' ');return roman+' '+zh}return 'China destination '+zh}
function cityKeyFromDestination(value){return Object.keys(destinationProfiles).find(key=>value.includes(key)||value.includes(destinationProfiles[key].zh))}
function genericProfile(destination){const english=destination.split(/\s(?=[\u3400-\u9fff])/)[0]||destination;return{zh:destination.match(/[\u3400-\u9fff]+/)?.[0]||'',mood:'LOCAL CHINA · DISCOVERY',description:'Explore '+english+' through its best-known landscapes, local culture and everyday flavors. Each stop is marked for live map verification before booking.',sights:[`Official landmark in ${destination}`,`Local cultural site in ${destination}`,`Signature natural scenery near ${destination}`,`Historic neighborhood in ${destination}`,`Local craft or food experience in ${destination}`,`Easy day trip from ${destination}`],foods:[`Local breakfast in ${destination}`,`Regional specialty meal in ${destination}`,`Local tea or dessert in ${destination}`],stay:`Central ${destination}, close to the main transport hub`}}
function getProfile(destination){const key=cityKeyFromDestination(destination);return key?destinationProfiles[key]:genericProfile(destination)}

function showCity(key){const data=destinationProfiles[key];if(!data)return;$$('.city-bubble').forEach(button=>button.classList.toggle('active',button.dataset.city===key));$('#previewImage').src=data.image;$('#previewImage').alt=key+' travel scenery';$('#previewMood').textContent=data.mood;$('#previewName').innerHTML=esc(key)+' <small>'+esc(data.zh)+'</small>';$('#previewDescription').textContent=data.description;$('#previewPlan').innerHTML='Plan a '+esc(key)+' trip <span>→</span>';$('#previewPlan').dataset.city=key}
$$('.city-bubble').forEach(button=>{button.addEventListener('mouseenter',()=>showCity(button.dataset.city));button.addEventListener('focus',()=>showCity(button.dataset.city));button.addEventListener('click',()=>showCity(button.dataset.city))});
$('#previewPlan').addEventListener('click',()=>{selectPopularCity($('#previewPlan').dataset.city||'Beijing');$('#planner').scrollIntoView({behavior:'smooth'})});

function fillSelect(select,items,placeholder,formatter=englishName){select.innerHTML='<option value="">'+placeholder+'</option>'+items.map(item=>'<option value="'+esc(item)+'">'+esc(formatter(item))+'</option>').join('')}
function addSpecialRegions(){divisionData['香港特别行政区']||={'香港特别行政区':['中西区','湾仔区','油尖旺区','九龙城区','离岛区']};divisionData['澳门特别行政区']||={'澳门特别行政区':['大堂区','望德堂区','风顺堂区','嘉模堂区','路凼填海区']};divisionData['台湾省']||={'台北市':['中正区','大安区','信义区','士林区','北投区'],'台中市':['中区','西区','北屯区','西屯区'],'台南市':['中西区','安平区','东区'],'高雄市':['新兴区','三民区','左营区'],'花莲县':['花莲市','新城乡','寿丰乡'],'台东县':['台东市','成功镇','池上乡']}}
function updateDestination(){const province=$('#province').value,city=$('#prefecture').value,county=$('#county').value,chosen=county||city||province;const label=englishName(chosen);$('#destination').value=label;$('#selectionSummary').textContent='Selected: '+label}
function updateCounties(){const items=divisionData[$('#province').value]?.[$('#prefecture').value]||[];fillSelect($('#county'),items,'Whole city / area');updateDestination()}
function updateCities(){const items=Object.keys(divisionData[$('#province').value]||{});fillSelect($('#prefecture'),items,'Choose a city or area');$('#county').innerHTML='<option value="">Whole city / area</option>';updateDestination()}
async function selectPopularCity(key){const pair=popularLocations[key];if(!pair||!divisionData[pair[0]])return;$('#province').value=pair[0];updateCities();$('#prefecture').value=pair[1];updateCounties();updateDestination()}

async function initDivisions(){
  const pinyinReady=import('https://esm.sh/pinyin-pro@3.27.0').then(module=>{
    pinyinFn=module.pinyin;
    if(Object.keys(divisionData).length){
      const province=$('#province').value,city=$('#prefecture').value,county=$('#county').value;
      fillSelect($('#province'),Object.keys(divisionData),'Choose a province or region');
      $('#province').value=province;updateCities();$('#prefecture').value=city;updateCounties();$('#county').value=county;updateDestination();
    }
  }).catch(error=>console.warn('Pinyin helper unavailable; using bilingual fallbacks.',error));
  try{const response=await fetch('./pca.json');if(!response.ok)throw new Error('Region data could not be loaded.');divisionData=await response.json();addSpecialRegions();fillSelect($('#province'),Object.keys(divisionData),'Choose a province or region');$('#province').value='浙江省';updateCities();$('#prefecture').value='杭州市';updateCounties()}catch(error){$('#province').innerHTML='<option value="浙江省">Zhejiang 浙江省</option>';$('#prefecture').innerHTML='<option value="杭州市">Hangzhou 杭州</option>';$('#county').innerHTML='<option value="">Whole city / area</option>';updateDestination();toast('Region list is temporarily unavailable. Hangzhou is ready to plan.')}
  void pinyinReady;
}
$('#province').addEventListener('change',updateCities);$('#prefecture').addEventListener('change',updateCounties);$('#county').addEventListener('change',updateDestination);
$$('.step').forEach(button=>button.addEventListener('click',()=>{$$('.step').forEach(item=>item.classList.toggle('active',item===button));$('#'+button.dataset.stepTarget).scrollIntoView({behavior:'smooth',block:'center'})}));

const worldOrigins=[
  'New York, United States','Los Angeles, United States','San Francisco, United States','Chicago, United States','Seattle, United States','Boston, United States','Washington, D.C., United States','Honolulu, United States','Toronto, Canada','Vancouver, Canada','Montreal, Canada','Mexico City, Mexico','São Paulo, Brazil','Rio de Janeiro, Brazil','Buenos Aires, Argentina','Santiago, Chile','Lima, Peru',
  'London, United Kingdom','Paris, France','Amsterdam, Netherlands','Brussels, Belgium','Berlin, Germany','Frankfurt, Germany','Munich, Germany','Madrid, Spain','Barcelona, Spain','Lisbon, Portugal','Rome, Italy','Milan, Italy','Zurich, Switzerland','Vienna, Austria','Prague, Czechia','Warsaw, Poland','Copenhagen, Denmark','Stockholm, Sweden','Oslo, Norway','Helsinki, Finland','Dublin, Ireland','Athens, Greece','Istanbul, Türkiye','Moscow, Russia',
  'Tokyo, Japan','Osaka, Japan','Seoul, South Korea','Singapore','Bangkok, Thailand','Kuala Lumpur, Malaysia','Jakarta, Indonesia','Bali, Indonesia','Manila, Philippines','Hanoi, Vietnam','Ho Chi Minh City, Vietnam','Phnom Penh, Cambodia','Delhi, India','Mumbai, India','Bengaluru, India','Kathmandu, Nepal','Dubai, United Arab Emirates','Doha, Qatar','Tel Aviv, Israel','Riyadh, Saudi Arabia',
  'Sydney, Australia','Melbourne, Australia','Brisbane, Australia','Perth, Australia','Auckland, New Zealand','Cairo, Egypt','Cape Town, South Africa','Johannesburg, South Africa','Nairobi, Kenya','Casablanca, Morocco','Lagos, Nigeria',
  'Beijing, China','Shanghai, China','Guangzhou, China','Shenzhen, China','Hong Kong, China','Macao, China','Taipei, Taiwan'
];
$('#worldOrigins').innerHTML=worldOrigins.map(city=>`<option value="${esc(city)}"></option>`).join('');
$('#locationHelp').textContent='Only after you click: your browser asks permission, then coordinates are sent once to our location lookup provider to identify the nearest city. We do not save the coordinates. You can always search worldwide instead.';
$('#locateOrigin').addEventListener('click',()=>{
  const button=$('#locateOrigin'),status=$('#locationStatus');
  if(!navigator.geolocation){status.textContent='Location is not supported in this browser. Search for your city instead.';return}
  button.disabled=true;button.querySelector('span').textContent='Locating…';status.textContent='Your browser will ask for permission.';
  navigator.geolocation.getCurrentPosition(async position=>{
    const {latitude,longitude}=position.coords;
    try{
      const response=await fetch(`https://api.bigdatacloud.net/data/reverse-geocode-client?latitude=${latitude}&longitude=${longitude}&localityLanguage=en`);
      if(!response.ok)throw new Error('Location lookup failed');
      const place=await response.json(),city=place.city||place.locality||place.principalSubdivision||'Current location',country=place.countryName||'';
      $('#origin').value=[city,country].filter(Boolean).join(', ');status.textContent=`Located near ${$('#origin').value}. You can edit this before planning.`;toast('Starting point added from your location.')
    }catch(error){status.textContent='We found your position but could not identify the city. Search for a nearby city instead.'}
    button.disabled=false;button.querySelector('span').textContent='Use my location';
  },error=>{
    status.textContent=error.code===1?'Location permission was not granted. Search for your city instead.':'We could not determine your location. Search for your city instead.';
    button.disabled=false;button.querySelector('span').textContent='Use my location';
  },{enableHighAccuracy:false,timeout:12000,maximumAge:300000});
});

function tripInput(){const start=new Date($('#startDate').value),end=new Date($('#endDate').value);const days=Math.max(1,Math.round((end-start)/86400000)+1);const destination=$('#destination').value;return{destination,days,travelers:Math.max(1,+$('#travelers').value||1),budget:$('#budget').value,transport:$('#transport').value,origin:$('#origin').value.trim()||'your arrival point',interests:$$('#interestChips input:checked').map(input=>input.value),notes:$('#notes').value.trim(),profile:getProfile(destination)}}
function costModel(input,style,index){const tiers={value:{stay:280,food:120,local:55},comfort:{stay:520,food:220,local:110},premium:{stay:1100,food:420,local:240}};const base=tiers[input.budget],tickets=style==='Deep Dive'?220:style==='Slow China'?90:150,arrival=index===0?(input.transport.includes('rail')?420:input.transport.includes('Flight')?900:520):0;return{transport:base.local+arrival,stay:base.stay,food:base.food,sights:tickets,total:base.local+arrival+base.stay+base.food+tickets}}
function buildDay(input,index,variant){const profile=input.profile,shift=variant==='Deep Dive'?1:variant==='Slow China'?2:0,a=profile.sights[(index+shift)%profile.sights.length],b=profile.sights[(index+shift+1)%profile.sights.length],food=profile.foods[index%profile.foods.length],cost=costModel(input,variant,index);const timeline=[];if(index===0)timeline.push(['Arrival',`Travel from ${input.origin} to ${input.destination}. Allow extra time for passport checks, station security and finding the correct exit.`]);timeline.push(['Morning',`${a}. Start before the main crowds and keep the Chinese name ready for tickets and map searches.`],['Lunch',`${food}. Ask the hotel to write the restaurant name in Chinese if needed.`],['Afternoon',`${b}. Keep 30–45 minutes of buffer for transfers and entrance checks.`],['Evening',`${profile.foods[(index+1)%profile.foods.length]}, followed by an easy return to ${profile.stay}.`]);if(index===input.days-1)timeline.push(['Departure','Confirm the station or airport terminal in Chinese and arrive early.']);return{a,b,food,cost,timeline}}
function createPlans(input){const configs=[{name:'China Essentials',label:'BEST FIRST TRIP',summary:'Iconic sights, local food and efficient connections.',score:94},{name:'Deep Dive',label:'MORE CONTEXT',summary:'Fewer places, longer visits and more cultural depth.',score:90},{name:'Slow China',label:'LOWER PACE',summary:'Gentler mornings, neighborhood time and flexible buffers.',score:87}];return configs.map(config=>({...config,days:Array.from({length:input.days},(_,index)=>buildDay(input,index,config.name))}))}
function planTotal(plan,input){return plan.days.reduce((sum,day)=>sum+day.cost.total,0)*input.travelers}
function renderRoutes(input){currentPlans=createPlans(input);$('#resultsIntro').textContent=`${input.days} days in ${input.destination} · ${input.travelers} traveler${input.travelers>1?'s':''}`;$('#routeGrid').innerHTML=currentPlans.map((plan,index)=>`<article class="route-card ${index===0?'featured':''}"><span class="route-badge">${plan.label}</span><p class="kicker">${String(index+1).padStart(2,'0')} / ITINERARY</p><h3>${plan.name}</h3><p>${plan.summary}</p><div class="route-facts"><span>Daily pace <b>${index===0?'Balanced':index===1?'Focused':'Relaxed'}</b></span><span>Transport <b>${esc(input.transport)}</b></span><span>Stay <b>${esc(input.profile.stay)}</b></span></div><ol class="route-preview">${plan.days.slice(0,3).map((day,dayIndex)=>`<li>Day ${dayIndex+1}: ${esc(day.a)}</li>`).join('')}</ol><p class="route-price">Estimated total <b>${money(planTotal(plan,input))}</b></p><button class="primary select-route" data-plan="${index}" type="button">Choose this itinerary <span>→</span></button></article>`).join('');$$('.select-route').forEach(button=>button.addEventListener('click',()=>selectRoute(+button.dataset.plan,input)));$('#results').classList.remove('hidden');$('#finalPlan').classList.add('hidden');$('#results').scrollIntoView({behavior:'smooth'})}
function selectRoute(index,input){selectedPlan=currentPlans[index];const totals=selectedPlan.days.reduce((sum,day)=>{Object.keys(sum).forEach(key=>sum[key]+=day.cost[key]);return sum},{transport:0,stay:0,food:0,sights:0,total:0});Object.keys(totals).forEach(key=>totals[key]*=input.travelers);$('#finalSubtitle').textContent=`${selectedPlan.name} · ${input.days} days · ${input.destination}`;$('#budgetStrip').innerHTML=[['Transport',totals.transport],['Stays',totals.stay],['Food',totals.food],['Sights',totals.sights],['Trip total',totals.total]].map(item=>`<div class="budget-item"><small>${item[0]}</small><b>${money(item[1])}</b></div>`).join('');$('#dayList').innerHTML=selectedPlan.days.map((day,index)=>`<article class="day-card"><div class="day-index"><small>DAY</small>${String(index+1).padStart(2,'0')}</div><div><h3>${esc(day.a)} + ${esc(day.b)}</h3><div class="timeline">${day.timeline.map(row=>`<div class="timeline-row"><b>${row[0]}</b><span>${esc(row[1])}</span></div>`).join('')}</div><div class="day-meta"><div><b>Transport</b>${esc(input.transport)} · ${money(day.cost.transport*input.travelers)}</div><div><b>Stay</b>${esc(input.profile.stay)} · ${money(day.cost.stay*input.travelers)}</div><div><b>Food + sights</b>${money((day.cost.food+day.cost.sights)*input.travelers)}</div></div></div></article>`).join('');$('#mapCheck').href='https://uri.amap.com/search?keyword='+encodeURIComponent(input.destination)+'&src=china-trip-planner';$('#finalPlan').classList.remove('hidden');$('#finalPlan').scrollIntoView({behavior:'smooth'});saveChosenPlan(input,selectedPlan,totals);toast('Your detailed China itinerary is ready.')}
$('#tripForm').addEventListener('submit',event=>{event.preventDefault();const input=tripInput();if(!$('#province').value||!$('#prefecture').value)return toast('Choose a province and city first.');renderRoutes(input)});$('#editTrip').addEventListener('click',()=>$('#planner').scrollIntoView({behavior:'smooth'}));

function localPlans(){try{return JSON.parse(localStorage.getItem('chinaTripPlans')||'[]')}catch{return[]}}
function renderSaved(){const plans=localPlans();if(!plans.length)return;$('#savedTrips').className='';$('#savedTrips').innerHTML=plans.map(plan=>`<article class="saved-trip"><div><b>${esc(plan.destination)}</b><br><small>${esc(plan.name)} · ${plan.days} days · ${new Date(plan.savedAt).toLocaleDateString('en-US')}</small></div><span>${money(plan.total)}</span></article>`).join('')}
async function saveChosenPlan(input,plan,totals){const record={destination:input.destination,name:plan.name,days:input.days,total:totals.total,savedAt:new Date().toISOString()};const existing=localPlans().filter(item=>!(item.destination===record.destination&&item.name===record.name));localStorage.setItem('chinaTripPlans',JSON.stringify([record,...existing].slice(0,8)));renderSaved();if(currentUser&&supabase){const {error}=await supabase.from('user_travel_plan_history').insert({user_id:currentUser.id,destination:input.destination,route_name:plan.name,plan_data:{input,plan,totals}});if(error)console.warn('Cloud save unavailable; plan remains saved on this device.',error)}}

function openAuth(){if(currentUser){toast('You are already signed in.');return}$('#authDialog').showModal()}$('#authButton').addEventListener('click',openAuth);$('#savedAuthButton').addEventListener('click',openAuth);
function setAuthMode(mode){authMode=mode;$$('[data-auth-mode]').forEach(button=>button.classList.toggle('active',button.dataset.authMode===mode));$('#confirmLabel').classList.toggle('hidden',mode!=='register');$('#authSubmit').textContent=mode==='register'?'Create account':'Sign in';$('#authStatus').textContent=''}$$('[data-auth-mode]').forEach(button=>button.addEventListener('click',()=>setAuthMode(button.dataset.authMode)));
async function initAuth(){try{const module=await import('https://esm.sh/@supabase/supabase-js@2.57.4');supabase=module.createClient('https://snsfmpcomwkrqcofbssa.supabase.co','sb_publishable_bDB5kn2d3f9azvxvGlDMfg_HSoZSD84');const {data}=await supabase.auth.getSession();if(data.session)showUser(data.session.user);supabase.auth.onAuthStateChange((_event,session)=>{if(session)showUser(session.user)})}catch(error){console.warn('Account service unavailable; trip planning still works.',error)}}
function showUser(user){currentUser=user;const name=user.user_metadata?.username||'Traveler';$('#authButton').textContent=name+' · Signed in';if($('#authDialog').open)$('#authDialog').close();toast('Welcome back, '+name+'.')}
$('#authForm').addEventListener('submit',async event=>{event.preventDefault();if(!supabase)return $('#authStatus').textContent='Account service is temporarily unavailable. You can still plan as a guest.';const username=$('#username').value.trim(),password=$('#password').value;if(!/^[A-Za-z0-9_]{3,24}$/.test(username))return $('#authStatus').textContent='Use 3–24 letters, numbers or underscores.';if(authMode==='register'&&password!==$('#confirmPassword').value)return $('#authStatus').textContent='Passwords do not match.';$('#authStatus').textContent=authMode==='register'?'Creating your account…':'Signing you in…';const email=username.toLowerCase()+'@travel-planner.app';const result=authMode==='register'?await supabase.auth.signUp({email,password,options:{data:{username}}}):await supabase.auth.signInWithPassword({email,password});if(result.error)return $('#authStatus').textContent=(authMode==='register'?'Account creation failed. ':'Sign-in failed. ')+result.error.message;if(result.data.session)showUser(result.data.user);else $('#authStatus').textContent='Account created. Sign in to continue.'});

const today=new Date(),end=new Date();end.setDate(today.getDate()+4);$('#startDate').value=today.toISOString().slice(0,10);$('#endDate').value=end.toISOString().slice(0,10);showCity('Beijing');renderSaved();await initDivisions();initAuth();
